# Generated by Django 5.1.3 on 2024-11-29 16:45

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "post_uuid",
                    models.UUIDField(unique=True, verbose_name="게시글 UUID"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="제목"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="users.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글 목록",
            },
        ),
        migrations.CreateModel(
            name="PostDailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "date",
                    timescale.db.models.fields.TimescaleDateTimeField(
                        interval="1 day", verbose_name="날짜"
                    ),
                ),
                (
                    "daily_view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="일별 조회수"
                    ),
                ),
                (
                    "daily_like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="일별 좋아요 수"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_statistics",
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 일별 통계",
                "verbose_name_plural": "게시글 일별 통계 목록",
            },
        ),
        migrations.CreateModel(
            name="PostStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="전체 조회수"
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="전체 좋아요 수"
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="posts.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시글 전체 통계",
                "verbose_name_plural": "게시글 전체 통계 목록",
            },
        ),
    ]
