# Generated by Django 5.1.4 on 2024-12-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_delete_poststatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="released_at",
            field=models.DateTimeField(
                null=True, verbose_name="게시글 업로드 일시"
            ),
        ),
    ]
