# Generated by Django 5.1.4 on 2025-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_released_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="게시글 슬러그",
            ),
        ),
    ]
