# Generated by Django 5.1.6 on 2025-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="게시글 활성화 여부, 삭제된 게시글의 soft delete에 사용합니다.",
                verbose_name="활성화 여부",
            ),
        ),
    ]
