# Generated by Django 5.1.3 on 2024-11-29 16:45

from django.db import migrations, models

from utils.utils import generate_random_group_id


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "velog_uuid",
                    models.UUIDField(unique=True, verbose_name="사용자 UUID"),
                ),
                (
                    "access_token",
                    models.TextField(verbose_name="Access Token"),
                ),
                (
                    "refresh_token",
                    models.TextField(verbose_name="Refresh Token"),
                ),
                (
                    "group_id",
                    models.IntegerField(
                        blank=True,
                        default=generate_random_group_id,
                        verbose_name="그룹 ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="활성 여부"
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
            },
        ),
    ]
