# Generated by Django 5.1.6 on 2025-03-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="로그인용 QR 토큰",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="QR Code 유효 기간(기본값 5분 후)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, verbose_name="사용 여부"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="요청한 IP 주소",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="요청한 디바이스 정보",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="로그인 요청한 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR 로그인 토큰",
                "verbose_name_plural": "QR 로그인 토큰 목록",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="qr_login_token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_qr_token",
                to="users.qrlogintoken",
                verbose_name="QR 로그인 토큰",
            ),
        ),
        migrations.AddIndex(
            model_name="qrlogintoken",
            index=models.Index(
                fields=["token"], name="users_qrlog_token_8cbbb1_idx"
            ),
        ),
    ]
