# Generated by Django 5.1.6 on 2025-03-19 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_qrlogintoken_user_qr_login_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrlogintoken",
            name="user",
        ),
    ]
