# Generated by Django 5.1.6 on 2025-03-20 00:16

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_qrlogintoken_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="qr_login_token",
        ),
        migrations.AddField(
            model_name="qrlogintoken",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_login_tokens",
                to="users.user",
                verbose_name="로그인 요청한 사용자",
            ),
        ),
        migrations.AlterField(
            model_name="qrlogintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    3,
                    20,
                    0,
                    21,
                    22,
                    700016,
                    tzinfo=datetime.timezone.utc,
                ),
                help_text="QR Code 유효 기간(기본값 5분 후)",
            ),
        ),
    ]
