# Generated by Django 5.1.6 on 2025-03-21 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_qrlogintoken_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrlogintoken",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="QR Code 생성 일시",
            ),
        ),
    ]
