# Generated by Django 5.1.6 on 2025-03-21 23:17

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_qrlogintoken_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrlogintoken",
            name="expires_at",
            field=models.DateTimeField(
                default=users.models.default_expires_at,
                help_text="QR Code 유효 기간을 의미합니다. 기본값으로  5분 후 시간으로 자동 설정 됩니다.",
                verbose_name="QR Code 유효 기간",
            ),
        ),
    ]
