# Generated by Django 5.1.6 on 2025-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_qrlogintoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="velog 에서 사용자가 지정한 이름입니다.",
                max_length=255,
                null=True,
                verbose_name="사용자 이름",
            ),
        ),
    ]
