# Generated by Django 5.1.6 on 2025-06-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="thumbnail",
            field=models.CharField(
                blank=True,
                help_text="velog 에서 사용자가 지정한 thumbnail url 값입니다.",
                max_length=255,
                null=True,
                verbose_name="사용자 썸네일",
            ),
        ),
    ]
