# Generated by Django 5.1.3 on 2024-12-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEventTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("01", "로그인"),
                            ("02", "포스트 클릭"),
                            ("03", "포스트 그래프 클릭"),
                            ("04", "종료"),
                            ("99", "nothing"),
                        ],
                        default="99",
                        help_text="어떤 이벤트 타입인지 저장하는 필드입니다.",
                        max_length=2,
                        verbose_name="이벤트타입",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_tracks",
                        to="users.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
