# Generated by Django 5.1.3 on 2024-12-07 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usereventtracking",
            options={
                "verbose_name": "사용자 이벤트",
                "verbose_name_plural": "사용자 이벤트 목록",
            },
        ),
    ]
