# Generated by Django 5.1.4 on 2024-12-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_alter_usereventtracking_options"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStayTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loaded_at", models.DateTimeField(verbose_name="진입 일시")),
                (
                    "unloaded_at",
                    models.DateTimeField(verbose_name="퇴출 일시"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_staytimes",
                        to="users.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 체류시간",
                "verbose_name_plural": "사용자 체류시간 목록",
            },
        ),
    ]
