# Generated by Django 5.1.4 on 2024-12-18 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_userstaytime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstaytime",
            name="created_at",
        ),
    ]
