# Generated by Django 5.1.6 on 2025-05-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0011_alter_qrlogintoken_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(verbose_name="주 시작일"),
                ),
                ("week_end_date", models.DateField(verbose_name="주 종료일")),
                (
                    "insight",
                    models.JSONField(
                        default=dict,
                        help_text="주간 트렌드에 대한 핵심 키워드 및 인사이트 데이터, schema 변동에 유연하게 대응하기 위해 JSONField 사용",
                        verbose_name="핵심 키워드",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, verbose_name="처리 완료 여부"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 완료 시간"
                    ),
                ),
            ],
            options={
                "verbose_name": "주간 트렌드",
                "verbose_name_plural": "주간 트렌드 목록",
                "indexes": [
                    models.Index(
                        fields=["week_start_date"],
                        name="insight_wee_week_st_edef88_idx",
                    ),
                    models.Index(
                        fields=["is_processed"],
                        name="insight_wee_is_proc_6ab048_idx",
                    ),
                ],
                "unique_together": {("week_start_date", "week_end_date")},
            },
        ),
        migrations.CreateModel(
            name="UserWeeklyTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(verbose_name="주 시작일"),
                ),
                ("week_end_date", models.DateField(verbose_name="주 종료일")),
                (
                    "insight",
                    models.JSONField(
                        default=dict,
                        help_text="주간 트렌드에 대한 핵심 키워드 및 인사이트 데이터, schema 변동에 유연하게 대응하기 위해 JSONField 사용",
                        verbose_name="핵심 키워드",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, verbose_name="처리 완료 여부"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 완료 시간"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_insights",
                        to="users.user",
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 주간 인사이트",
                "verbose_name_plural": "사용자 주간 인사이트 목록",
                "indexes": [
                    models.Index(
                        fields=["user"], name="insight_use_user_id_5ef5a8_idx"
                    ),
                    models.Index(
                        fields=["week_start_date"],
                        name="insight_use_week_st_32d1cd_idx",
                    ),
                    models.Index(
                        fields=["is_processed"],
                        name="insight_use_is_proc_c1098d_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "week_start_date", "week_end_date")
                },
            },
        ),
    ]
