# Generated by Django 5.1.6 on 2025-02-24 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotiPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="제목"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="본문"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="체크 해제 시 비공개 상태가 됩니다. (admin에서만 확인 가능)",
                        verbose_name="활성 상태",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지글",
                "verbose_name_plural": "공지글",
            },
        ),
    ]
