# Generated by Django 5.1.6 on 2025-05-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noti", "0001_initial"),
        ("users", "0011_alter_qrlogintoken_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotiMailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="생성 일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="수정 일시"
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="메일 제목"),
                ),
                ("body", models.TextField(verbose_name="메일 내용")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="발송 시간"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(
                        default=False, verbose_name="발송 성공 여부"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="오류 메시지"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="users.user",
                        verbose_name="수신자",
                    ),
                ),
            ],
            options={
                "verbose_name": "메일 발송 로그",
                "verbose_name_plural": "메일 발송 로그 목록",
            },
        ),
    ]
