# Generated by Django 5.1.6 on 2025-06-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noti", "0002_notimaillog"),
        ("users", "0011_alter_qrlogintoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notimaillog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="users.user",
                verbose_name="수신자",
            ),
        ),
    ]
